--- #YAML:1.0
name:               Pod-Thread
version:            1.00
abstract:           Convert POD data to the HTML macro language thread
author:
    - Russ Allbery <rra@stanford.edu>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    perl:         5.008
    Pod::Simple:  3.06
    Readonly:     0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
