---
abstract: 'Convert POD data to thread HTML macro language'
author:
  - 'Russ Allbery <rra@stanford.edu>'
build_requires: {}
configure_requires:
  Module::Build: 0.28
dynamic_config: 1
generated_by: 'Module::Build version 0.4005, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pod-Thread
provides:
  Pod::Thread:
    file: lib/Pod/Thread.pm
    version: 0
requires:
  Pod::Simple: 3.06
  Readonly: 0
  perl: 5.008
resources:
  license: http://dev.perl.org/licenses/
version: 1.01
