---
abstract: 'Convert POD data to the HTML macro language thread'
author:
  - 'Russ Allbery <rra@cpan.org>'
build_requires:
  Perl6::Slurp: '0'
configure_requires:
  Module::Build: '0.28'
dynamic_config: 1
generated_by: 'Module::Build version 0.4231, CPAN::Meta::Converter version 2.150010'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Pod-Thread
provides:
  Pod::Thread:
    file: lib/Pod/Thread.pm
    version: '3.00'
requires:
  Pod::Simple: '3.06'
  perl: '5.024'
resources:
  bugtracker: https://github.com/rra/pod-thread/issues
  homepage: https://www.eyrie.org/~eagle/software/pod-thread/
  license: http://www.opensource.org/licenses/mit-license.php
  repository: https://github.com/rra/pod-thread.git
version: '3.00'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
